#!/bin/bash

echo "Windows向けビルド設定"
echo "==================="
echo ""
echo "Unity Editorで以下の設定を行ってください:"
echo ""
echo "1. File > Build Settings を開く"
echo "2. Platform で 'Windows' を選択"
echo "3. 'Switch Platform' をクリック"
echo ""
echo "4. Player Settings で以下を設定:"
echo "   - Company Name: YourCompany"
echo "   - Product Name: SchoolLoveSimulator"
echo "   - Default Icon: (アイコン画像を設定)"
echo "   - Resolution and Presentation:"
echo "     - Default Screen Width: 1920"
echo "     - Default Screen Height: 1080"
echo "     - Fullscreen Mode: Windowed"
echo "   - Splash Image: (スプラッシュ画像を設定)"
echo ""
echo "5. Quality Settings:"
echo "   - Rendering > Anti Aliasing: 4x Multi Sampling"
echo "   - Shadows: Hard and Soft Shadows"
echo ""
echo "6. Build Settings:"
echo "   - Target Platform: Windows"
echo "   - Architecture: x86_64"
echo "   - Compression Method: LZ4HC"
echo ""
echo "7. ビルド出力先: $(pwd)/Builds/Windows/"
echo ""
echo "準備ができたら 'Build' ボタンをクリックしてビルドを開始してください。"